/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/drives": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List indexed drives
         * @description Drives in the index, with online/offline state refreshed against disk.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Drive"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List a logical directory
         * @description Immediate children (files + synthesized subdirectories) of a path on a drive.
         */
        get: {
            parameters: {
                query: {
                    /** @description Drive id */
                    drive: string;
                    /** @description Forward-slash path; empty = drive root */
                    path?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DirEntry"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Describe one logical path */
        get: {
            parameters: {
                query: {
                    drive: string;
                    path: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DirEntry"];
                    };
                };
                /** @description No such path */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reverse-index query (paginated)
         * @description Query content grouped by hash. All filters are optional and AND together.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Coarse file type category, e.g. image, video, audio, application, text */
                    type?: string;
                    /** @description File extension, e.g. cr2 */
                    ext?: string;
                    /** @description Hash prefix */
                    hash?: string;
                    /** @description Only content present on this drive id */
                    drive?: string;
                    /** @description Only content with no copy on a currently-online drive */
                    offline?: boolean;
                    /** @description Only content carrying this metadata key */
                    key?: string;
                    /** @description Together with key */
                    value?: string;
                    /** @description Only content carrying this user tag */
                    tag?: string;
                    /** @description Only favorites */
                    favorite?: boolean;
                    limit?: number;
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QueryRow"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/content/{hash}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream a file's bytes
         * @description Streams the bytes of one copy of the content (prefers an online drive).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Content hash (full, or a unique-enough prefix) */
                    hash: components["parameters"]["Hash"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description File bytes */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/octet-stream": string;
                    };
                };
                /** @description Hash not indexed or no readable copy online */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/content/{hash}/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full detail for a content hash */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Content hash (full, or a unique-enough prefix) */
                    hash: components["parameters"]["Hash"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ContentDetail"];
                    };
                };
                /** @description Hash not indexed */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/thumb/{hash}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a thumbnail
         * @description Returns a JPEG thumbnail, generating and caching it on demand if missing.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Content hash (full, or a unique-enough prefix) */
                    hash: components["parameters"]["Hash"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Thumbnail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/jpeg": string;
                    };
                };
                /** @description No thumbnail available (e.g. undecodable format) */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/content/{hash}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add tags (write)
         * @description Requires the server to be started with `--allow-write`.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Content hash (full, or a unique-enough prefix) */
                    hash: components["parameters"]["Hash"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        tags: string[];
                    };
                };
            };
            responses: {
                /** @description The hash's full tag list after the change */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string[];
                    };
                };
                403: components["responses"]["WritesDisabled"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/content/{hash}/tags/{tag}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a tag (write) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Content hash (full, or a unique-enough prefix) */
                    hash: components["parameters"]["Hash"];
                    tag: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Remaining tags */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string[];
                    };
                };
                403: components["responses"]["WritesDisabled"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/content/{hash}/favorite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark as favorite (write) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Content hash (full, or a unique-enough prefix) */
                    hash: components["parameters"]["Hash"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Favorited */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                403: components["responses"]["WritesDisabled"];
            };
        };
        /** Clear favorite (write) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Content hash (full, or a unique-enough prefix) */
                    hash: components["parameters"]["Hash"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Unfavorited */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                403: components["responses"]["WritesDisabled"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Link hashes (write)
         * @description Link two or more hashes into one group (e.g. a JPG + its RAW). Overlapping groups merge.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        hashes: string[];
                    };
                };
            };
            responses: {
                /** @description The resulting group id */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            group?: string;
                        };
                    };
                };
                403: components["responses"]["WritesDisabled"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/links/{hash}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Unlink a hash (write) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Content hash (full, or a unique-enough prefix) */
                    hash: components["parameters"]["Hash"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Whether the hash had been linked */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            unlinked?: boolean;
                        };
                    };
                };
                403: components["responses"]["WritesDisabled"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/content/{hash}/dedup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dedup — keep one copy, delete the others (write, destructive)
         * @description Keeps the copy at (keep_drive, keep_path) and deletes the other on-disk copies of this hash, leaving a `<file>.dedup` pointer beside each removed file (matching the CLI). Offline copies are skipped. Requires `--allow-write` and an explicit `confirm: true`.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Content hash (full, or a unique-enough prefix) */
                    hash: components["parameters"]["Hash"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        keep_drive: string;
                        /** @description Forward-slash path on keep_drive */
                        keep_path: string;
                        /** @description Must be true; this deletes files */
                        confirm: boolean;
                    };
                };
            };
            responses: {
                /** @description What was kept/removed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DedupOutcome"];
                    };
                };
                /** @description confirm was not true */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                403: components["responses"]["WritesDisabled"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Drive: {
            drive_id?: string;
            label?: string;
            /** @description Last filesystem path the drive was indexed at */
            last_root?: string;
            /** Format: date-time */
            first_seen?: string;
            /** Format: date-time */
            last_seen?: string;
            online?: boolean;
            detached?: boolean;
            /** @description Number of location rows on this drive */
            files?: number;
        };
        /** @description A file or a synthesized subdirectory in a logical listing. */
        DirEntry: {
            name: string;
            /** @enum {string} */
            kind: "file" | "dir";
            /** @description Present for files */
            algo?: string | null;
            /** @description Present for files */
            hash?: string | null;
            /** @description Present for files (bytes) */
            size?: number | null;
            file_type?: string | null;
            ext?: string | null;
            /** @description Present for files */
            has_thumb?: boolean | null;
            /** @description Present for directories: files beneath it */
            file_count?: number | null;
        };
        /** @description One content hash plus where/how it appears. */
        QueryRow: {
            algo?: string;
            hash?: string;
            file_type?: string | null;
            ext?: string | null;
            size?: number;
            /** @description Number of copies recorded */
            locations?: number;
            /** @description Any copy on a currently-online drive */
            online?: boolean;
            has_thumb?: boolean;
            /** @description Comma-separated drive ids holding this hash */
            drives?: string;
            /** @description A representative path */
            sample_path?: string;
            /** @description Comma-separated user tags */
            tags?: string;
            /** @description Link group id if linked */
            link_group?: string | null;
        };
        ContentDetail: {
            algo?: string;
            hash?: string;
            size?: number;
            file_type?: string | null;
            ext?: string | null;
            /** Format: date-time */
            extracted_at?: string;
            has_thumb?: boolean;
            metadata?: components["schemas"]["MetaTag"][];
            locations?: components["schemas"]["Location"][];
            tags?: string[];
            /** @description Other hashes linked to this one */
            links?: string[];
        };
        MetaTag: {
            /** @description Family-0 group, e.g. EXIF, File, PNG */
            group?: string;
            key?: string;
            /** @description Human-readable rendering */
            value?: string;
        };
        Location: {
            drive_id?: string;
            /** @description Forward-slash path relative to the drive root */
            path?: string;
            online?: boolean;
        };
        DedupOutcome: {
            /** @description drive_id:path of the kept copy */
            kept?: string;
            /** @description drive_id:path of each removed copy */
            removed?: string[];
            /** @description Copies left because their drive is offline */
            skipped_offline?: number;
        };
    };
    responses: {
        /** @description Server was not started with `--allow-write` */
        WritesDisabled: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
    };
    parameters: {
        /** @description Content hash (full, or a unique-enough prefix) */
        Hash: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
